---
- name: Install docker-py module
  pip:
    name:
      - docker-py
    state: latest
    extra_args: "--no-cache-dir"
  when:
    - ansible_python_version is version('2.6', '<=')

- name: Install docker module
  pip:
    name:
      - docker
    state: latest
    extra_args: "--no-cache-dir"
  when:
    - ansible_python_version is version('2.6', '>')
