---
- name: docker-prune | create systemd timer and service for clean useless docker data
  template:
    src: "{{ item }}"
    dest: "{{ item | regex_replace('.j2','') }}"
    backup: no
    owner: root
    group: root
    mode: 0644
  loop:
    - etc/systemd/system/docker-prune.service.j2
    - etc/systemd/system/docker-prune.timer
  notify:
    - prune docker
