---
- name: docker-shim | get current version when installed
  shell: |
    set -o pipefail
    sudo -Hu nobody timeout 5 docker --version 2>&1 | grep -Eoi '([0-9]{1,}\.){2,3}[0-9]{1,}(|-[a-z0-9\.]{1,})' | sort -urV | head -1
  args:
    executable: /bin/bash
  register: docker_current_version
  changed_when: false
  check_mode: false

- name: docker-shim | Setup shim if required
  block:
    - name: docker-shim | Ensure containerd service dir exists
      file:
        path: /etc/systemd/system/containerd.service.d
        state: directory
    - name: docker-shim | Add shim to ensure Docker can start in all environments.
      template:
        src: etc/systemd/system/containerd.service.d/override.conf.j2
        dest: /etc/systemd/system/containerd.service.d/override.conf
  notify:
    - restart docker
  when:
    - docker_current_version.stdout is version('19.03.2', '<=')

- name: docker-shim | Delete shim when it outdated
  file:
    path: /etc/systemd/system/containerd.service.d/override.conf
    state: absent
  register: docker_service_override_template
  notify:
    - restart docker
  when:
    - docker_current_version.stdout is version('19.03.2', '>')
