---
- name: lazydocker | check binary installed
  stat:
    path: "{{ lazydocker_path }}"
  changed_when: no
  register: lazydocker_current_binary

- name: lazydocker | get current binary version
  shell: |
    sudo -Hu nobody timeout 2 {{ lazydocker_path }} --version 2>&1 | grep -Eoi '([0-9]{1,}\.){1,3}[0-9]{1,}(|-[a-z0-9]{1,})' | sort -uV | head -1
  register: lazydocker_current_version
  changed_when: no
  when:
    - lazydocker_current_binary.stat.exists

- name: lazydocker | download with unarchive when upgrade or downgrade
  unarchive:
    src: "{{ lazydocker_url }}"
    dest: "{{ lazydocker_path | dirname }}"
    exclude:
      - 'README.md'
      - 'LICENSE'
    remote_src: yes
    force: yes
    owner: root
    mode: 0755
  when:
    - not lazydocker_current_binary.stat.exists or (lazydocker_current_version.stdout and lazydocker_current_version.stdout is version(lazydocker_version, '!='))
